### ISSUE TITLE
Error while kniting: In citation_package_arg(citation_package)

### ISSUE THREAD

**Issue by beatrizmilz** [LatinR/latinr#11]
Hi @eliocamp ! I just installed the package and created a file using the template, but when I knit it, I get this error:

Do you know if I need to make anything else in order for it to work? I'm using MacOS
```
output file: Untitled.knit.md

! LaTeX Error: Environment CSLReferences undefined.

Error: LaTeX failed to compile Untitled.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Untitled.log for more info.
In addition: Warning message:
In citation_package_arg(citation_package) :
  citation_package = 'none' was deprecated; please use 'default' instead.
Execution halted
```

Thank you :)

**Comment by beatrizmilz** [comment]
Also, the template is showing 'LatinR 2020'

**Comment by eliocamp** [comment]
Yep. Sorry, I hadn't got the time to update latinr to 2021. I'l try to fix this asap.
