### ISSUE TITLE
Sumisión (envío)

### ISSUE THREAD

**Issue by rociojoo** [LatinR/latinr#5]
Hola Elio, tengo el siguiente error:
_Submitting
Error: Unknown field names: first_name4, last_name4, email4, country4, Affiliation4, first_name5, last_name5, email5, country5, Affiliation5, first_name6, last_name6, email6, country6, Affiliation6, first_name7, last_name7, email7, country7, Affiliation7__

¿No puedo tener tantos coautores?

**Comment by eliocamp** [comment]
Hola, deberías poder, pero se ve que hay algún error. Trato de arreglarlo en estos días.

**Comment by eliocamp** [comment]
rociojoo, en la última versión debería estar arreglado. Fijate y cualquier problema reportalo acá.

**Comment by rociojoo** [comment]
¡Gracias! Éxito... es decir, lo logré y tuve confirmación por mail que es lo importante, pero lo raro es que al final del mensaje me sale error:

Submitting
LatinR2020 Submission XX

`
Error in strsplit(submission, ";", fixed = TRUE) : non-character argument
`

Eso no sé de dónde viene. Imagino que no es un problema para mí, pero lo reporto por si te interesa.

Gracias otra vez.

**Comment by eliocamp** [comment]
Gracias!
